### PR TITLE
Fixing errors in the parser

### PR DESCRIPTION
**Pull request by jaytaph**
Fixing and finetuning some parts of the parser to make more tests pass.

### CODE REVIEW

**Comment by emwalker** [comment]
@jaytaph these changes seem fine.  I took the liberty of pushing a commit to your branch to run `make fix`, get the tests passing and add in some of the other tests [mentioned here](https://gosubgroup.slack.com/archives/C05VBA3CXRN/p1697639108872929).  Feel free to drop that commit.

**Comment by emwalker** [comment]
Can you rebase and clean these commits up so that they pass the checks, or, alternatively, squash everything when you merge?

**Review by emwalker — APPROVED** [review]
LGTM with fixes and cleaning up the commits (or squashing them into a single commit).

**Comment by emwalker** [comment]
Looks like broken checkpoint commits made it into `main`.  Let me know @jaytaph if this isn't a concern, and I won't bother people about it.

**Comment by jaytaph** [comment]
I think I squash-merged it, so i'm not sure why that happened.

**Comment by emwalker** [comment]
No worries.  I'll continue bothering people about it in that case. :)

**Comment by emwalker** [comment]
My mistake.  It looks like the checkpoint commits were squashed after all:

**Pull request merged**
