### PR TITLE
fixed the issue with character slicing

### LINKED ISSUE #138: Error when slicing a string at an arbitrary byte index without considering character boundaries
I ran into an issue while running the parser for the [wikipedia page](https://en.wikipedia.org/wiki/Cargo_cult_programming). 

```sh
thread 'main' panicked at src/html5_parser/tokenizer/character_reference.rs:331:49:
byte index 32 is not a char boundary; it is inside '–' (bytes 30..33) of `amp; Company</a>. pp.&#160;338–3`
```

Reproduction Link:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=be21cf401750d068dbeea6327310388b

I was able to fix this issue by using `.char_indices` method.
```rust
    fn find_entity(&mut self) -> Option<String> {
        let s = self.stream.look_ahead_slice(*LONGEST_ENTITY_LENGTH);
        for (i, _) in s.char_indices().rev(){
            if TOKEN_NAMED_CHARS.contains_key(&s[0..i]) {
                // Move forward with the number of chars matching
                // self.stream.skip(i);
                return Some(String::from(&s[0..i]));
            }
        }
        None
    }
   ```
   
  However, that failed 30 test cases.
  ```sh
  failures:
    html5_parser::tokenizer::character_reference::tests::entity_100
    html5_parser::tokenizer::character_reference::tests::entity_102
    html5_parser::tokenizer::character_reference::tests::entity_103
    html5_parser::tokenizer::character_reference::tests::entity_104
    html5_parser::tokenizer::character_reference::tests::entity_106
    html5_parser::tokenizer::character_reference::tests::entity_109
    html5_parser::tokenizer::character_reference::tests::entity_200
    html5_parser::tokenizer::character_reference::tests::entity_204
    html5_parser::tokenizer::character_reference::tests::entity_208
    html5_parser::tokenizer::character_reference::tests::entity_209
    html5_parser::tokenizer::character_reference::tests::entity_210
    html5_parser::tokenizer::character_reference::tests::entity_211
    html5_parser::tokenizer::character_reference::tests::entity_214
    html5_parser::tokenizer::character_reference::tests::entity_217
    html5_parser::tokenizer::character_reference::tests::entity_220
    html5_parser::tokenizer::character_reference::tests::entity_222
    html5_parser::tokenizer::character_reference::tests::entity_224
    html5_parser::tokenizer::character_reference::tests::entity_226
    html5_parser::tokenizer::character_reference::tests::entity_228
    html5_parser::tokenizer::character_reference::tests::entity_230
    html5_parser::tokenizer::character_reference::tests::entity_232
    html5_parser::tokenizer::character_reference::tests::entity_234
    html5_parser::tokenizer::character_reference::tests::entity_236
    html5_parser::tokenizer::character_reference::tests::entity_238
    html5_parser::tokenizer::character_reference::tests::entity_240
    html5_parser::tokenizer::character_reference::tests::entity_242
    html5_parser::tokenizer::character_reference::tests::entity_244
    html5_parser::tokenizer::character_reference::tests::entity_246
    html5_parser::tokenizer::character_reference::tests::entity_248
    html5_parser::tokenizer::character_reference::tests::entity_250
```

I want to fix this issue and submit a PR. I would appreciate any suggestions or advice on fixing this issue. 

Thank You

### PR DESCRIPTION
**Pull request by dibashthapa**
fixes #138

### CODE REVIEW

**Review by jaytaph — APPROVED** [review]

**Review by emwalker — APPROVED** [review]
LGTM.

```
$ make fix # nothing changes
$ make test # runs, as we already knew
```

**Comment by emwalker** [comment]
When this PR is merged, we'll either want to rebase out the checkpoint commit with the failing test, or we'll want to squash it.

**Comment by jaytaph** [comment]
@dibashthapa thanks for the pr. Could you sign the commit so we can merge it?

**Comment by dibashthapa** [comment]
@jaytaph Done

**Comment by jaytaph** [comment]
@dibashthapa thanks for the pr!

**Pull request merged**
