### PR TITLE
Node file structure

### PR DESCRIPTION
**Pull request by lucalewin**
PR for issue #120

While doing this I thought that maybe the files in the now `node/data` directory could be combined into the `node/data.rs` file since they are quite short. This could reduce overall complexity. Or are these files growing in size in the future?

### CODE REVIEW

**Comment by Kiyoshika** [comment]
The `ElementData` struct will slowly grow over time (I am currently working on migrating stuff from `Document` to here right now), the others might grow slightly but not very large. Maybe in the future I will consolidate them, but for now I will keep them separate

**Comment by Kiyoshika** [comment]
Also, it seems this has failed some of the formatting checks, could you run `make test` locally and resolve the issues?

**Comment by lucalewin** [comment]
should work now

**Comment by Kiyoshika** [comment]
cool, I'm good with this. I added @jaytaph to review and merge if he's also good with it. Thanks!

**Review by emwalker — APPROVED** [review]

**Comment by jaytaph** [comment]
lgtm. @lucalewin Thanks for the PR!

**Pull request merged**
