### PR TITLE
added 3 test case to token.rs

### PR DESCRIPTION
**Pull request by ankush1233**
i did the make fix

### CODE REVIEW

**Comment by jaytaph** [comment]
@ankush1233 Thanks for the PR. Could you run "make fix" to fix up the formatting of the code?

**Comment by ankush1233** [comment]
why this is showing ? this Rust CI / fmt (pull_request) i did make fix everything ran successfully then i did cargo fmt -- --check
no error nothing can u please say me whats the problem? and how can i solve the problem?

**Comment by jaytaph** [comment]
Couldnit be possible that you run a different version of rust? I see a few small space issues in the github action. I think this would show up with a make fix (note thatif there are changes, you must commit them manually)

**Comment by emwalker** [comment]
@ankush1233 I'm seeing something similar to what CI is showing:



Let me know if you'd like someone to push a fix to your branch.

**Comment by ankush1233** [comment]
Can u do it?

**Comment by emwalker** [comment]
@ankush1233 I might not be able to push the change, now that I think about it, because the PR is generated from a branch in your own copy of the repo.  But here is the patch you can apply to your own code:

```patch
commit 35d79f299454eaed8366c8bc06bc4db53a91637d
Author: Eric Walker <eric.walker@gmail.com>
Date:   Mon Nov 6 20:10:52 2023 -0700

    Fix linting issues

diff --git a/src/html5/tokenizer/token.rs b/src/html5/tokenizer/token.rs
index 54c48be..49de83d 100644
--- a/src/html5/tokenizer/token.rs
+++ b/src/html5/tokenizer/token.rs
@@ -221,10 +221,10 @@ mod tests {
         let token = Token::Eof;
         assert_eq!(format!("{}", token), "EOF");
     }
-    
+
     #[test]
     fn test_is_start_tag() {
-        let token = Token::StartTag{
+        let token = Token::StartTag {
             name: "div".to_string(),
             is_self_closing: false,
             attributes: HashMap::new(),
@@ -232,10 +232,10 @@ mod tests {
         assert!(token.is_start_tag("div"));
         assert!(!token.is_start_tag("span"));
     }
-    
+
     #[test]
     fn test_is_any_start_tag() {
-        let start_tag = Token::StartTag{
+        let start_tag = Token::StartTag {
             name: "div".to_string(),
             is_self_closing: false,
             attributes: HashMap::new(),
@@ -244,11 +244,11 @@ mod tests {
         assert!(start_tag.is_any_start_tag());
         assert!(!other_tag.is_any_start_tag());
     }
-    
+
     #[test]
     fn test_is_text_token() {
         let text_token = Token::Text("TestingText".to_string());
-        let other_token = Token::StartTag{
+        let other_token = Token::StartTag {
             name: "div".to_string(),
             is_self_closing: false,
             attributes: HashMap::new(),
```

You'll probably want to figure out what's going on in your environment.  I'd run these commands to see if they do anything:
```sh
$ make fix
$ git status
```

**Comment by emwalker** [comment]
Ok, we got past one hurdle with the updating of `patch-2`.  Now it looks like you'll need to fix your branch and make sure the tests run.

**Comment by emwalker** [comment]
@ankush1233 ok, it seems you've corrected the Rust syntax errors.  Now you'll want to do three more things:

1. Add [commit signing in GitHub](https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key) and Git, so that your commits are signed
1. Try that `make fix` command again, but this time run it on the `patch-2` branch
1. Rebase your commits into a single commit so that the commit is signed

**Comment by jaytaph** [comment]
This pr has been idle a while. I am closing in favor for #276 which merges @ankush1233 work in the core.  If you happen to read this, thanks for the work on this PR!

**Pull request closed without merging**
