### PR TITLE
Update node_id to use pub(crate)

### PR DESCRIPTION
**Pull request by manish7017**
Issue #88

### CODE REVIEW

**Comment by jaytaph** [comment]
@manish7017 Thanks for the PR.. would you mind signing the commits so we can merge it? See [Learn more about signing commits.](https://docs.github.com/articles/about-gpg/) for more information

**Comment by jaytaph** [comment]
@blaumeise20 @emwalker Seems that using a pub(crate) doesn't work. Any idea's on how to fix this, or should we leave it as pub for now?

**Comment by manish7017** [comment]
I will attempt to find the appropriate solution for pub(crate). In the meantime, let’s keep it as pub.

**Comment by blaumeise20** [comment]
@jaytaph pub(crate) only makes the field visible to the current crate, so if you try to use it in a different crate, it won't work. It only works if you have the tests directly in the same crate (preferably even the same file).

**Comment by blaumeise20** [comment]
Oh I see now that I looked at the code, I didn't mean the entire *struct* but the *field* of the struct.

**Comment by jaytaph** [comment]
This seems to work! 👍 If you could sign the commits, i'm happy to merge!

**Comment by emwalker** [comment]
I suspect we can use `let index: usize = node_id.into()` (or the equivalent) where we want access to the inner field.  But using `pub(crate)` is totally fine at this stage.  This PR is an improvement.

**Comment by manish7017** [comment]
Hello, can someone guide me on how to sign the remaining commits? This is my first time signing a commit.
I’ve been trying to sign the commit for the past 2-3 hours, but there’s still one left. Can someone guide me on this?

**Comment by Kiyoshika** [comment]
> Hello, can someone guide me on how to sign the remaining commits? This is my first time signing a commit.
> I’ve been trying to sign the commit for the past 2-3 hours, but there’s still one left. Can someone guide me on this?

Are you on MacOS? I just had to do this recently

**Comment by jaytaph** [comment]
There is a lot going on in this PR :-)

My suggestion would be not to try to fix it, but close this PR, and submit another one, since the change is small. The new commits seem to be signed, so that should not be an issue.

**Comment by jaytaph** [comment]
@manish7017 see previous comment

**Comment by emwalker** [comment]
To get it to work, you'll need to add a signature to GitHub and then either rebase your earlier commits or start a new PR.  (I'm away from my home laptop so I can't look at what might be going on with this PR until later today.)

**Comment by emwalker** [comment]
I agree with @jaytaph.  Probably best to just close this PR and create a new one.

**Pull request closed without merging**
