### PR TITLE
test(html): add html5 tests as git subtree

### LINKED ISSUE #187: Use git-subtree for vendoring html5lib-tests
Instead of copying the html5lib-tests inside our repository, it might be better to use a git subtree.

### PR DESCRIPTION
**Pull request by shubhexists**
Fixed #187 
Also corrected the mistake in the last Pull Request. It now has only the master branch in .git.

### CODE REVIEW

**Comment by emwalker** [comment]
I'm not very familiar with subtrees / submodules.  Is it expected that the files will still be there when switching to the PR branch, without having done anything further?



Also, I think the thought was to start with the CSS tests and then switch the HTML5 tests if the first experiment worked.  But I don't mind switching HTML5 tests over sooner if it's as simple as what I'm seeing in this PR.

**Comment by jaytaph** [comment]
> Also, I think the thought was to start with the CSS tests and then switch the HTML5 tests if the first experiment worked. But I don't mind switching HTML5 tests over sooner if it's as simple as what I'm seeing in this PR.

Yes, this is true.. I've added the issue on the issue-list, and it happens to be picked up before we had the chance on doing it for the css sub-tree..   There is still some issues to figure out on the git-side it seems with this PR.. but the idea is indeed that there is no change code-wise, git should automatically create the subtree when cloning the gosub repository

**Comment by shubhexists** [comment]
Hey @emwalker , 
if you clone my repository (shubhexists/gosub-engine),and navigate to `.git/refs/remotes` , you would see a html5lib-tests folder. 
This means that the repository is added as a subtree.

For reference, you would find only `origin` if you navigate to `.git/refs/remotes` in the main repository (gosub-browser/gosub-engine).

The benefit ?
You could just run `git pull html5lib-tests master` to pull any later commits from html5lib-tests repository.

**Comment by shubhexists** [comment]
Hello @jaytaph So, should I continue with the CSS Tests? 
Or there is more to think about if this is to be done or not?

**Comment by jaytaph** [comment]
> Hello @jaytaph So, should I continue with the CSS Tests? Or there is more to think about if this is to be done or not?

Lets try and fix this pr. I think were almost done, but it would be nice if you could rebase your commits as per @neuodev suggestion

**Comment by shubhexists** [comment]
KK, will do as soon as I get time

**Comment by emwalker** [comment]
> Hey @emwalker , if you clone my repository (shubhexists/gosub-engine),and navigate to .git/refs/remotes , you would see a html5lib-tests folder. This means that the repository is added as a subtree.

This is [what I'm seeing on the branch in your repo](https://github.com/shubhexists/gosub-engine/tree/main/tests) used for this PR:



I suspect you need to delete this directory from the branch in order for the subtree / submodule to be fully configured.  I could be wrong.

**Comment by shubhexists** [comment]
> > Hey @emwalker , if you clone my repository (shubhexists/gosub-engine),and navigate to .git/refs/remotes , you would see a html5lib-tests folder. This means that the repository is added as a subtree.
> 
> This is [what I'm seeing on the branch in your repo](https://github.com/shubhexists/gosub-engine/tree/main/tests) used for this PR:
> 
> 
> 
> I suspect you need to delete this directory from the branch in order for the subtree / submodule to be fully configured. I could be wrong.

So basically there are 3 commits in this PR. 
If you look at the very 1st Commit of this pull request... 
It has deleted this `data/html5lib` directory.

These files are then added back in the third commit of this PR. ( This time as a sub tree. Directly from tests repository. )
Just for clear reference, here are the commands I ran (AFTER DELETING THE data/html5lib-tests DIRECTORY)- 

1) `git remote add html5lib-tests https://github.com/html5lib/html5lib-tests -t master` 
This line adds the master branch of html5lib repo into our git...
2) `git fetch html5lib-tests`
Fetching
3) `git subtree add --prefix=tests/data/html5lib-tests html5lib-tests master --squash`
Here is when the contents of the repositories are bought back in....

Here is a reference link I used - https://www.atlassian.com/git/tutorials/git-subtree

**Comment by emwalker** [comment]
Ah, ok.  So it sounds like even with a subtree, the sources are checked into our repo.  That was the detail I wasn't understanding.  Thanks for clarifying the process.  (I think I was confusing subtrees with submodules.)

**Comment by shubhexists** [comment]
> > Also, I think the thought was to start with the CSS tests and then switch the HTML5 tests if the first experiment worked. But I don't mind switching HTML5 tests over sooner if it's as simple as what I'm seeing in this PR.
> 
> Yes, this is true.. I've added the issue on the issue-list, and it happens to be picked up before we had the chance on doing it for the css sub-tree.. There is still some issues to figure out on the git-side it seems with this PR.. but the idea is indeed that there is no change code-wise, git should automatically create the subtree when cloning the gosub repository

Hey! Should I add the CSS tests in a data/css repository..
I might take the repository that was discussed in the Slack 
https://github.com/CourtBouillon/css-parsing-tests
Kindly Confirm...

**Comment by jaytaph** [comment]
Discussed with @shubhexists on slack: the pr made is actually correct with the 3 commits. To make sure there are no merge/rebase pollutions, @shubhexists will make a new pr with the subtree change (results in 3 commits and no file-changes), and we will merge that. Once completed, @shubhexists can do yhe same thing for the css.

**Pull request closed without merging**
