### PR TITLE
pass more tests

### PR DESCRIPTION
**Pull request by CharlesChen0823**
add more test, but found the method  `run_adoption_agency` might have some problem.

### CODE REVIEW

**Comment by jaytaph** [comment]
@CharlesChen0823  Thanks for the PR..  The adoption_agency is a nasty algorithm to get right. I assume there are still a few things not quite right yet but fortunately we have good tests to check this.

**Comment by jaytaph** [comment]
@CharlesChen0823 are you also on slack, maybe we can coordinate parser fixes so we don't do the same tests? :)

**Comment by CharlesChen0823** [comment]
> @CharlesChen0823 are you also on slack, maybe we can coordinate parser fixes so we don't do the same tests? :)

Because network problem, I cannot directly connect slack. 
I had rewrite the adoption_agency_algorithm and find the appropriate insert place method,  and current the implement pass more test, except template case and fragment parser case. because for simple, current not support template case in my implement.

I will send an new PR soon.

**Comment by jaytaph** [comment]
we can move to discussions otherwise: https://github.com/gosub-browser/gosub-engine/discussions/182

**Pull request merged**
